// Generated by CoffeeScript 1.8.0
(function() {
  var Sprite, extend;

  extend = require('extend');

  Sprite = (function() {
    "use strict";
    Sprite.prototype._defaults = {
      width: 64,
      height: 64,
      offset: 0,
      imgPath: '',
      imgHeight: null,
      frame: 30
    };

    function Sprite(el, opts) {
      this.el = el;
      this.opts = extend({}, this._defaults, opts);
      this.el.style.background = "url(" + this.opts.imgPath + ") no-repeat 0 0";
      this._offsetAll = (this.opts.frame + 1) * this.opts.offset;
    }

    Sprite.prototype.update = function(num) {
      var pos;
      pos = -((this.opts.imgHeight - this._offsetAll) / this.opts.frame * num + (this.opts.offset * num) + this.opts.offset);
      this.el.style.backgroundPosition = "0 " + pos + "px";
      return this;
    };

    return Sprite;

  })();

  if (typeof define === 'function' && define.amd) {
    define(function() {
      return Sprite;
    });
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = Sprite;
  } else {
    window.Sprite || (window.Sprite = Sprite);
  }

}).call(this);
